Repository dmlc/dgl, pull requests merged in 2023-01, with the labels that each got.

#5101 [API Deprecation] Remove _deprecation module
  python/dgl/__init__.py
  python/dgl/_deprecate/__init__.py
  python/dgl/_deprecate/frame.py
  python/dgl/_deprecate/graph.py
  python/dgl/_deprecate/kernel.py
  python/dgl/_deprecate/nodeflow.py
  python/dgl/_deprecate/runtime/__init__.py
  python/dgl/_deprecate/runtime/adapter.py
  python/dgl/_deprecate/runtime/degree_bucketing.py
  python/dgl/_deprecate/runtime/ir/__init__.py
  python/dgl/_deprecate/runtime/ir/executor.py
  python/dgl/_deprecate/runtime/ir/program.py
  python/dgl/_deprecate/runtime/ir/registry.py
  python/dgl/_deprecate/runtime/ir/var.py
  python/dgl/_deprecate/runtime/runtime.py
  python/dgl/_deprecate/runtime/scheduler.py
  python/dgl/_deprecate/runtime/spmv.py
  python/dgl/_deprecate/udf.py
  python/dgl/_deprecate/view.py
  python/dgl/backend/mxnet/tensor.py
  python/dgl/backend/pytorch/tensor.py
  python/dgl/backend/tensorflow/tensor.py
  python/dgl/function/message.py
  python/dgl/function/reducer.py
  python/dgl/network.py
  python/dgl/transforms/functional.py
Labels: Release Candidate, deprecate

#5098 [Dist] Allow reading and writing single-column vector Parquet files.
  tests/tools/test_dist_part.py
  tests/tools/utils.py
  tools/distpartitioning/array_readwriter/parquet.py
Labels: Release Candidate

#5091 [Example][Refactor] Multi-gpu graphsage link prediction example refactor
  examples/pytorch/graphsage/advanced/README.md
  examples/pytorch/graphsage/advanced/pure_gpu_node_classification.py
  examples/pytorch/graphsage/advanced/train_sampling_unsupervised.py
  examples/pytorch/multigpu/README.md
  examples/pytorch/multigpu/multi_gpu_link_prediction.py
Labels: Release Candidate

#5106 [Sparse] Change CMakeFiles to build DGL Sparse for multiple PyTorch versions
  CMakeLists.txt
  dgl_sparse/CMakeLists.txt
  dgl_sparse/build.bat
  dgl_sparse/build.sh
  dgl_sparse/src/sparse_matrix.cc
Labels: Release Candidate, Sparse API

#4829 [Bug] Fix NN modules crashing with non-FP32 inputs (reopen #4262)
  python/dgl/nn/pytorch/conv/appnpconv.py
  python/dgl/nn/pytorch/conv/atomicconv.py
  python/dgl/nn/pytorch/conv/chebconv.py
  python/dgl/nn/pytorch/conv/densegraphconv.py
  python/dgl/nn/pytorch/conv/densesageconv.py
  python/dgl/nn/pytorch/conv/gcn2conv.py
  python/dgl/nn/pytorch/conv/graphconv.py
  python/dgl/nn/pytorch/conv/sgconv.py
  python/dgl/nn/pytorch/conv/tagconv.py
  python/dgl/nn/pytorch/conv/twirlsconv.py
Labels: Release Candidate

#5102 [CI] updgrade pytorch version for benchmark CI
  Jenkinsfile
  benchmarks/run.sh
  benchmarks/scripts/build_dgl_asv.sh
  benchmarks/scripts/generate_excel.py
  benchmarks/scripts/install_dgl_asv.sh
  benchmarks/scripts/publish.sh
  benchmarks/scripts/torch_gpu_pip.txt
  docker/Dockerfile.ci_benchmark
  docker/install/ubuntu_install_conda.sh
Labels: Release Candidate

#5108 [Sparse] Remove SparseMatrix.indices and add device/dtype conversions
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/diag_matrix.py
  python/dgl/sparse/sparse_matrix.py
  tests/pytorch/sparse/test_diag.py
  tests/pytorch/sparse/test_elementwise_op_diag.py
  tests/pytorch/sparse/test_sparse_matrix.py
Labels: Release Candidate

#5118 [API Deprecation] Remove _dataloading and tgcn example
  examples/pytorch/tgn/README.md
  examples/pytorch/tgn/data_preprocess.py
  examples/pytorch/tgn/dataloading.py
  examples/pytorch/tgn/modules.py
  examples/pytorch/tgn/tgn.py
  examples/pytorch/tgn/train.py
  python/dgl/__init__.py
  python/dgl/_dataloading/__init__.py
  python/dgl/_dataloading/cluster_gcn.py
  python/dgl/_dataloading/dataloader.py
  python/dgl/_dataloading/negative_sampler.py
  python/dgl/_dataloading/neighbor.py
  python/dgl/_dataloading/pytorch/__init__.py
  python/dgl/_dataloading/pytorch/dataloader.py
  python/dgl/_dataloading/shadow.py
Labels: Release Candidate

#4747 [Optimization] Optimize bias term in SageConv layer
  python/dgl/nn/pytorch/conv/sageconv.py
Labels: Release Candidate

#4483 [DataLoader] Allow batch_size=None for GraphDataLoader
  python/dgl/dataloading/dataloader.py
  tests/pytorch/test_dataloader.py
  tests/pytorch/test_nn.py
Labels: Release Candidate

#5122 CVE-2007-4559 Patch
  python/dgl/data/utils.py
Labels: Release Candidate

#5127 [BugFix] fix unexpected exception when agg_type is GCN and bias disabled
  python/dgl/nn/pytorch/conv/sageconv.py
Labels: Release Candidate

#5128 [Release] Update versioning with local CUDA version suffix
  python/update_version.py
Labels: Release Candidate

#5135 [Sparse] Remove unnecessary API exposure.
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/elementwise_op_diag.py
  python/dgl/sparse/elementwise_op_sp.py
Labels: Release Candidate

#5136 [Sparse] Update doc string of element-wise ops for DiagMatrix and SparseMatrix.
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/elementwise_op.py
Labels: Release Candidate

#5134 [Bugfix] Avoid initializing CUDA context at importing
  python/dgl/backend/pytorch/sparse.py
Labels: Release Candidate

#5140 [CI] fix bugs for multigpu benchmarks
  benchmarks/benchmarks/multigpu/bench_multigpu_rgcn.py
  benchmarks/benchmarks/utils.py
  benchmarks/scripts/build_dgl_asv.sh
  benchmarks/scripts/publish.sh
  docker/Dockerfile.ci_benchmark
Labels: Release Candidate

#5139 [Bugfix] Fix the call of tar.extractall() method
  python/dgl/data/utils.py
  tests/compute/test_data.py
Labels: Release Candidate

#5142 [Sparse] Add elementwise mul and div method, and polish the python doc.
  python/dgl/sparse/elementwise_op.py
Labels: Release Candidate

#5149 [Sparse] Further polish the doc string.
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/elementwise_op.py
Labels: Release Candidate

#5150 [Sparse] Further polish.
  python/dgl/sparse/elementwise_op.py
Labels: Release Candidate

#5133 [Bugfix] Typo in version update
  python/update_version.py
Labels: Release Candidate

#5143 [Sparse] Reduce peak memory of SpSpAdd.
  dgl_sparse/src/elemenwise_op.cc
Labels: Release Candidate

#5147 [Sparse] Use efficient implementation for diagonal and sparse matrices multiplication.
  python/dgl/sparse/matmul.py
  tests/pytorch/sparse/test_matmul.py
Labels: Release Candidate

#5158 [Build] Change regex pattern to include local versions in update_version.py
  python/update_version.py
Labels: Release Candidate

#5157 Replace global cudaStream in Filter with runtime calls (fix #5153)
  src/array/cuda/cuda_filter.cu
  tests/compute/test_filter.py
Labels: Release Candidate

#5154 [CI] fix device configure when run on GPU
  benchmarks/benchmarks/api/bench_edge_subgraph.py
  benchmarks/benchmarks/api/bench_in_subgraph.py
  benchmarks/benchmarks/api/bench_node_subgraph.py
  benchmarks/benchmarks/api/bench_sample_neighbors.py
Labels: Release Candidate

#5171 [Doc] remove deprected Node/EdgeDataLoader
  docs/source/api/python/dgl.dataloading.rst
Labels: Release Candidate

#5169 [Sparse] Fix sddmm docstring
  python/dgl/sparse/sddmm.py
Labels: Release Candidate

#5163 [Sparse] Make functions compatible with PyTorch scalar tensors
  python/dgl/sparse/elementwise_op.py
  python/dgl/sparse/elementwise_op_diag.py
  python/dgl/sparse/elementwise_op_sp.py
  python/dgl/sparse/utils.py
  tests/pytorch/sparse/test_elementwise_op_diag.py
  tests/pytorch/sparse/test_elementwise_op_sp.py
Labels: Release Candidate

#5170 [Sparse] Rename as_sparse to to_sparse, dense to to_dense.
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/diag_matrix.py
  python/dgl/sparse/elementwise_op_diag.py
  python/dgl/sparse/matmul.py
  python/dgl/sparse/sparse_matrix.py
  tests/pytorch/sparse/test_diag.py
  tests/pytorch/sparse/test_elementwise_op.py
  tests/pytorch/sparse/test_matmul.py
  tests/pytorch/sparse/test_sparse_matrix.py
  tests/pytorch/sparse/utils.py
Labels: Release Candidate

#5162 [Sparse] Refactor matmul interface.
  docs/source/api/python/dgl.sparse_v0.rst
  python/dgl/sparse/matmul.py
  tests/pytorch/sparse/test_matmul.py
Labels: Release Candidate

#5173 [Sparse] Support sparse matrix dividing scalar
  python/dgl/sparse/elementwise_op.py
  python/dgl/sparse/elementwise_op_sp.py
  tests/pytorch/sparse/test_elementwise_op_sp.py
Labels: Release Candidate

#5174 [Sparse] Use X to represent dense tensors in sddmm
  python/dgl/sparse/sddmm.py
Labels: Release Candidate

#5164 [Sparse] Sparse matrix subtraction
  python/dgl/sparse/elementwise_op.py
  python/dgl/sparse/elementwise_op_diag.py
  python/dgl/sparse/elementwise_op_sp.py
  tests/pytorch/sparse/test_elementwise_op.py
  tests/pytorch/sparse/test_elementwise_op_diag.py
Labels: Release Candidate

#5175 enable dgl sparse build in default
  CMakeLists.txt
  benchmarks/scripts/build_dgl_asv.sh
  tests/scripts/build_dgl.sh
Labels: Release Candidate

#5178 [Sparse] Polish diag_matrix.py and sparse_matrix.py.
  python/dgl/sparse/diag_matrix.py
  python/dgl/sparse/sparse_matrix.py
Labels: Release Candidate

#5179 [Sparse] Polish the docstring of SparseMatrix.csr() and SparseMatrix.csc()
  python/dgl/sparse/sparse_matrix.py
Labels: Release Candidate

#5180 [Sparse] Polish reduction.py.
  python/dgl/sparse/reduction.py
Labels: Release Candidate

#5177 [Sparse] polish strings of matmul.py and sddmm.py.
  python/dgl/sparse/matmul.py
  python/dgl/sparse/sddmm.py
Labels: Release Candidate

#5182 [Sparse] Polish softmax.py.
  python/dgl/sparse/softmax.py
Labels: Release Candidate

#5185 [Doc] Colab tutorial for graph diffusion
  docs/source/notebooks/sparse/graph_diffusion.nblink
  docs/source/notebooks/sparse/index.rst
  notebooks/sparse/graph_diffusion.ipynb
Labels: Release Candidate

#5188 [Doc] Colab tutorial for graph transformer
  docs/source/notebooks/sparse/graph_transformer.nblink
  docs/source/notebooks/sparse/index.rst
  notebooks/sparse/graph_transformer.ipynb
Labels: Release Candidate

#5206 [Sparse] Update HGNN notebook
  notebooks/sparse/hgnn.ipynb
Labels: Release Candidate, Sparse API

#5186 [Release] Conda/CMake changes for 1.0 release
  conda/dgl/meta.yaml
  dgl_sparse/build.bat
  python/update_version.py
Labels: Release Candidate

#5220 [Doc] Update colab tutorials with spmatrix
  notebooks/sparse/gcn.ipynb
  notebooks/sparse/graph_diffusion.ipynb
  notebooks/sparse/graph_transformer.ipynb
  notebooks/sparse/hgnn.ipynb
  notebooks/sparse/quickstart.ipynb
Labels: Release Candidate

#5213 [Doc] Update with Mono font to keep doc string consistent.
  python/dgl/sparse/diag_matrix.py
  python/dgl/sparse/matmul.py
  python/dgl/sparse/reduction.py
  python/dgl/sparse/softmax.py
  python/dgl/sparse/sparse_matrix.py
Labels: Release Candidate
