Repository dmlc/dgl, pull requests merged in 2023-02, with the labels that each got.

#5241 [Performance]Add concurrent cpu id hashmap
  src/array/cpu/id_hash_map.cc
  src/array/cpu/id_hash_map.h
  tests/cpp/test_id_hash_map.cc
Labels: Core Library Enhancement

#5304 [Enhancement] Change id hash map
  src/array/cpu/concurrent_id_hash_map.cc
  src/array/cpu/concurrent_id_hash_map.h
  tests/cpp/test_concurrent_id_hash_map.cc
Labels: system performance

#5130 [DistDGL] Memory optimization to reduce memory footprint of the Dist Graph partitioning pipeline.
  tools/distpartitioning/data_shuffle.py
Labels: Distributed Partitioning
