Repository dmlc/dgl, pull requests merged in 2024-08, with the labels that each got.

#7628 [GraphBolt] `QueryAndReplace` replaces `QueryAndThenReplace`.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
  graphbolt/src/partitioned_cache_policy.cc
  graphbolt/src/partitioned_cache_policy.h
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/feature_cache.py
  tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Labels: expedited

#7632 [GraphBolt][CUDA] Remove python thread from `overlap_graph_fetch`.
  python/dgl/graphbolt/base.py
  python/dgl/graphbolt/dataloader.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
Labels: expedited

#7634 [GraphBolt][CUDA] Optimize `CopyTo` performance.
  python/dgl/graphbolt/base.py
  python/dgl/graphbolt/dataloader.py
Labels: expedited

#7642 [GraphBolt][io_uring] Fix queue assignment bug.
  graphbolt/src/cnumpy.cc
Labels: expedited

#7644 [GraphBolt] Keep references valid in `CachePolicy`.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
  graphbolt/src/feature_cache.cc
  tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Labels: expedited

#7645 [GraphBolt] Enable exceptions for `gb::parallel_for`.
  graphbolt/include/graphbolt/async.h
Labels: expedited

#7647 [GraphBolt] Cleanup and refine `CachePolicy`.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
Labels: expedited

#7648 [GraphBolt] `CPUCachedFeature` no overlap fix.
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
Labels: expedited

#7646 [GraphBolt] Update `CPUCachedFeature` docstring.
  python/dgl/graphbolt/impl/cpu_cached_feature.py
Labels: expedited

#7649 [GraphBolt] Refactor `CachePolicy` more.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
  graphbolt/src/feature_cache.cc
  graphbolt/src/feature_cache.h
  python/dgl/graphbolt/impl/cpu_cached_feature.py
Labels: expedited

#7650 [GraphBolt] Temporary workaround for `CachePolicy`.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
Labels: expedited

#7651 [GraphBolt] Remove duplicate `CachePolicy::Insert` function.
  graphbolt/src/cache_policy.cc
  graphbolt/src/cache_policy.h
Labels: expedited

#7653 [GraphBolt] Remove assertions from `CachePolicy`.
  graphbolt/src/cache_policy.h
Labels: expedited

#7654 [GraphBolt] Lock-free `CachePolicy::ReadWriteCompleted`.
  graphbolt/src/cache_policy.h
  graphbolt/src/partitioned_cache_policy.cc
Labels: expedited

#7655 [GraphBolt] Move the function object into `gb::async`.
  graphbolt/include/graphbolt/async.h
Labels: expedited

#7656 [GraphBolt] Relax memory order of cache hit case.
  graphbolt/src/cache_policy.h
Labels: expedited

#7661 [GraphBolt] Add `gb::parallel_for_each`.
  graphbolt/include/graphbolt/async.h
  graphbolt/src/cnumpy.cc
  graphbolt/src/feature_cache.cc
  graphbolt/src/partitioned_cache_policy.cc
Labels: expedited

#7662 [GraphBolt][CUDA] Make fetching indices optional for NS.
  graphbolt/include/graphbolt/fused_sampled_subgraph.h
  graphbolt/src/cuda/neighbor_sampler.cu
  graphbolt/src/index_select.cc
Labels: expedited

#7665 [GraphBolt][CUDA] Fetch indices for NS later.
  graphbolt/include/graphbolt/cuda_sampling_ops.h
  graphbolt/include/graphbolt/fused_csc_sampling_graph.h
  graphbolt/src/cuda/neighbor_sampler.cu
  graphbolt/src/fused_csc_sampling_graph.cc
  python/dgl/graphbolt/dataloader.py
  python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
  tests/python/pytorch/graphbolt/test_dataloader.py
Labels: expedited

#7670 [GraphBolt] Implement proper `IndexSelectCSC` for CPU.
  graphbolt/src/fused_csc_sampling_graph.cc
  graphbolt/src/index_select.cc
Labels: expedited

#7669 [GraphBolt][CUDA] Enable `overlap_graph_fetch` in examples.
  examples/graphbolt/disk_based_feature/node_classification.py
  examples/graphbolt/node_classification.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
  examples/graphbolt/rgcn/hetero_rgcn.py
  examples/multigpu/graphbolt/node_classification.py
  python/dgl/graphbolt/dataloader.py
Labels: expedited

#7677 [GraphBolt][CUDA][Temporal] Complete implementation.
  graphbolt/include/graphbolt/cuda_sampling_ops.h
  graphbolt/include/graphbolt/fused_csc_sampling_graph.h
  graphbolt/src/cuda/neighbor_sampler.cu
  graphbolt/src/fused_csc_sampling_graph.cc
  python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
  python/dgl/graphbolt/impl/temporal_neighbor_sampler.py
  python/dgl/graphbolt/internal/sample_utils.py
Labels: expedited

#7680 [GraphBolt][io_uring] Use RAII to ensure queues are returned.
  graphbolt/src/cnumpy.cc
  graphbolt/src/cnumpy.h
Labels: expedited

#7681 [GraphBolt][CUDA] Refactor `overlap_graph_fetch`, simplify `gb.DataLoader`.
  examples/graphbolt/disk_based_feature/node_classification.py
  examples/graphbolt/node_classification.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
  examples/graphbolt/rgcn/hetero_rgcn.py
  examples/multigpu/graphbolt/node_classification.py
  python/dgl/graphbolt/dataloader.py
  python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
  tests/python/pytorch/graphbolt/test_dataloader.py
Labels: expedited

#7686 [GraphBolt][io_uring] Remove redundant mechanism.
  graphbolt/src/cnumpy.h
Labels: expedited

#7693 [GraphBolt][CUDA] Use same CUDA stream in async op.
  graphbolt/include/graphbolt/async.h
Labels: expedited

#7698 [GraphBolt][io_uring] Fix io_uring queue distribution bug.
  graphbolt/src/cnumpy.cc
  graphbolt/src/cnumpy.h
Labels: expedited

#7682 [GraphBolt][CUDA] Async sample neighbors and compaction.
  graphbolt/include/graphbolt/fused_csc_sampling_graph.h
  graphbolt/include/graphbolt/unique_and_compact.h
  graphbolt/src/fused_csc_sampling_graph.cc
  graphbolt/src/python_binding.cc
  graphbolt/src/unique_and_compact.cc
  python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  python/dgl/graphbolt/internal/sample_utils.py
  tests/python/pytorch/graphbolt/test_dataloader.py
Labels: expedited

#7699 [CUDA] Remove unused gpu_cache files and update.
  CMakeLists.txt
  graphbolt/CMakeLists.txt
  graphbolt/src/cuda/extension/gpu_cache.cu
  graphbolt/src/cuda/extension/gpu_cache.h
  graphbolt/src/python_binding.cc
  third_party/HugeCTR/gpu_cache/include/gpu_cache_api.hpp
  third_party/HugeCTR/gpu_cache/include/hash_functions.cuh
  third_party/HugeCTR/gpu_cache/include/nv_gpu_cache.hpp
  third_party/HugeCTR/gpu_cache/include/nv_util.h
  third_party/HugeCTR/gpu_cache/include/static_hash_table.hpp
  third_party/HugeCTR/gpu_cache/include/static_table.hpp
  third_party/HugeCTR/gpu_cache/include/uvm_table.hpp
  third_party/HugeCTR/gpu_cache/src/CMakeLists.txt
  third_party/HugeCTR/gpu_cache/src/nv_gpu_cache.cu
  third_party/HugeCTR/gpu_cache/src/static_hash_table.cu
  third_party/HugeCTR/gpu_cache/src/static_table.cu
  third_party/HugeCTR/gpu_cache/src/uvm_table.cu
  third_party/HugeCTR/gpu_cache/test/CMakeLists.txt
  third_party/HugeCTR/gpu_cache/test/cache_op_sol_test.cu
Labels: expedited

#7701 [GraphBolt][CUDA] Keep CUDAStream only if cuda is available.
  graphbolt/include/graphbolt/async.h
Labels: expedited

#7702 [GraphBolt][CUDA] Enable recent optimizations in the examples.
  examples/graphbolt/link_prediction.py
  examples/graphbolt/node_classification.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
  examples/graphbolt/rgcn/hetero_rgcn.py
Labels: expedited

#7705 [GraphBolt][CUDA] Eliminate GPUCache synchronization.
  graphbolt/src/cuda/extension/gpu_cache.cu
  graphbolt/src/cuda/extension/gpu_cache.h
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/impl/gpu_cache.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
Labels: expedited

#7706 [GraphBolt][CUDA] Enable asynchronous sampling for multigpu example.
  examples/multigpu/graphbolt/node_classification.py
Labels: expedited

#7707 [GraphBolt][CUDA] Use async for GPUGraphCache.
  graphbolt/src/cuda/extension/gpu_graph_cache.cu
  graphbolt/src/cuda/extension/gpu_graph_cache.h
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/impl/gpu_graph_cache.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/test_dataloader.py
Labels: expedited

#7712 [GraphBolt][CUDA] `gb::async` supports alternative streams now.
  graphbolt/include/graphbolt/async.h
  graphbolt/src/cuda/extension/gpu_cache.cu
  graphbolt/src/cuda/extension/gpu_graph_cache.cu
  graphbolt/src/fused_csc_sampling_graph.cc
  graphbolt/src/unique_and_compact.cc
Labels: expedited

#7709 [GraphBolt][CUDA] Eliminate synchronization for `overlap_graph_fetch`.
  graphbolt/src/index_select.cc
  graphbolt/src/index_select.h
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/test_dataloader.py
Labels: expedited

#7714 [GraphBolt][CUDA] Overlap original edge ids fetch.
  graphbolt/src/cuda/extension/gpu_graph_cache.cu
  graphbolt/src/cuda/extension/gpu_graph_cache.h
  python/dgl/graphbolt/impl/fused_csc_sampling_graph.py
  python/dgl/graphbolt/impl/gpu_graph_cache.py
  python/dgl/graphbolt/impl/neighbor_sampler.py
  tests/python/pytorch/graphbolt/impl/test_gpu_graph_cache.py
  tests/python/pytorch/graphbolt/impl/test_neighbor_sampler.py
Labels: expedited

#7719 [GraphBolt] Fix hetero sampling bug with single fanout.
  graphbolt/src/fused_csc_sampling_graph.cc
  tests/python/pytorch/graphbolt/impl/test_fused_csc_sampling_graph.py
Labels: expedited

#7723 [GraphBolt] Make `CachePolicy` hetero capable [1]
  graphbolt/src/partitioned_cache_policy.cc
  graphbolt/src/partitioned_cache_policy.h
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/feature_cache.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_feature_cache.py
Labels: expedited

#7730 [GraphBolt] `Feature.count()`.
  python/dgl/graphbolt/feature_store.py
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
  python/dgl/graphbolt/impl/torch_based_feature_store.py
  tests/python/pytorch/graphbolt/impl/test_basic_feature_store.py
  tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_disk_based_feature_store.py
  tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_torch_based_feature_store.py
Labels: expedited

#7731 [GraphBolt] `CachedFeature` can handle hetero features now.
  docs/source/api/python/dgl.graphbolt.rst
  examples/graphbolt/disk_based_feature/node_classification.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
  examples/multigpu/graphbolt/node_classification.py
  python/dgl/graphbolt/feature_store.py
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_cpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_gpu_cached_feature.py
  tests/python/pytorch/graphbolt/impl/test_hetero_cached_feature.py
Labels: expedited

#7722 [GraphBolt][PyG] Heterogenous example.
  examples/graphbolt/pyg/hetero/node_classification.py
Labels: expedited

#7733 [GraphBolt] Refine examples.
  examples/graphbolt/disk_based_feature/node_classification.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
Labels: expedited

#7732 [GraphBolt] `gb.DataLoader` can simply be a datapipe.
  python/dgl/graphbolt/dataloader.py
  tests/python/pytorch/graphbolt/test_dataloader.py
  tests/python/pytorch/graphbolt/test_integration.py
Labels: Release Candidate

#7735 [GraphBolt] Do not expose `CPUFeatureCache` storage tensor.
  graphbolt/src/feature_cache.h
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/impl/cpu_feature_cache.py
Labels: expedited

#7734 [GraphBolt] Minor improvement to item sampler and cache policy.
  graphbolt/src/cache_policy.h
  python/dgl/graphbolt/item_sampler.py
Labels: Release Candidate, expedited

#7739 [GraphBolt][Doc] Add `numpy_save_aligned` to documentation.
  docs/source/api/python/dgl.graphbolt.rst
Labels: expedited

#7741 [GraphBolt][Doc] Fix `read_async` doc display issue.
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
  python/dgl/graphbolt/impl/torch_based_feature_store.py
Labels: expedited

#7743 [GraphBolt][Doc] Fix `[gpu|cpu]_cached_feature` rendering.
  docs/source/api/python/dgl.graphbolt.rst
Labels: Release Candidate

#7745 [GraphBolt][PyG] Add `to_pyg` for layer input conversion.
  python/dgl/graphbolt/sampled_subgraph.py
  tests/python/pytorch/graphbolt/impl/test_sampled_subgraph_impl.py
Labels: expedited

#7748 [GraphBolt][CUDA] Fix error when empty env variable is used.
  python/dgl/graphbolt/__init__.py
Labels: expedited

#7751 [GraphBolt][Doc] Fix typo in documentation.
  python/dgl/graphbolt/impl/cpu_cached_feature.py
  python/dgl/graphbolt/impl/gpu_cached_feature.py
Labels: expedited

#7752 [GraphBolt][PyG] Link prediction example.
  examples/graphbolt/pyg/link_prediction.py
Labels: expedited

#7755 [Dist] move DistNode/EdgeDataLoader to distributed
  docs/source/api/python/dgl.dataloading.rst
  docs/source/api/python/dgl.distributed.rst
  docs/source/guide/distributed-apis.rst
  examples/distributed/graphsage/node_classification.py
  examples/distributed/graphsage/node_classification_unsupervised.py
  examples/distributed/rgcn/node_classification.py
  examples/pytorch/graphsage/dist/train_dist.py
  examples/pytorch/graphsage/dist/train_dist_transductive.py
  examples/pytorch/graphsage/dist/train_dist_unsupervised.py
  examples/pytorch/graphsage/dist/train_dist_unsupervised_transductive.py
  examples/pytorch/rgcn/experimental/entity_classify_dist.py
  python/dgl/data/citation_graph.py
  python/dgl/dataloading/__init__.py
  python/dgl/dataloading/dataloader.py
  python/dgl/dataloading/dist_dataloader.py
  python/dgl/distributed/__init__.py
  python/dgl/distributed/dist_dataloader.py
  tests/distributed/test_mp_dataloader.py
Labels: Release Candidate

#7756 [dev] make sure graphbolt is not imported together with dgl
  tests/python/test_dgl_import.py
  tests/scripts/task_unit_test.sh
Labels: Release Candidate

#7757 [GraphBolt][CUDA] Eliminate synchronization from exclude edges.
  examples/graphbolt/link_prediction.py
  examples/graphbolt/pyg/link_prediction.py
  graphbolt/include/graphbolt/cuda_ops.h
  graphbolt/include/graphbolt/isin.h
  graphbolt/src/cuda/isin.cu
  graphbolt/src/isin.cc
  graphbolt/src/python_binding.cc
  python/dgl/graphbolt/external_utils.py
  python/dgl/graphbolt/sampled_subgraph.py
  tests/python/pytorch/graphbolt/test_utils.py
Labels: Release Candidate, expedited

#7758 [GraphBolt][PyG] Add igb datasets to the examples.
  examples/graphbolt/pyg/labor/load_dataset.py
  examples/graphbolt/pyg/labor/node_classification.py
  examples/graphbolt/pyg/node_classification_advanced.py
Labels: expedited
